### PR TITLE
bump up versions for newlib, libgcc

### PR DESCRIPTION
**Pull request by JOE1994**
This PR makes the following changes
* bump up newlib: **2.5.0.20170421 => 3.0.0.20180831**
  Other versions of newlib newer than 3.0.0.20180831 causes the
  `lua_hello` example to fail, so I chose this version of newlib.
* bump up libgcc: **6.2.0 => 9.3.0**

I locally succeeded in rebuilding `newlib` &`libgcc` & examples using `gcc 7.5.0`.

Thank you for reviewing this PR :cake:

### CODE REVIEW

**Comment by ppannuto** [comment]
This is awesome! Thanks for looking into this, and I'm pleasantly surprised at how little had to change for things to still work!

> Other versions of newlib newer than 3.0.0.20180831 causes the lua_hello example to fail, so I chose this version of newlib.

Fail how? Do we have an understanding of why?

---

What other apps did you test with these changes? This necessarily touches pretty much every app, so it would be good to test out several and make sure nothing weird happened, especially given the lua issues.

**Comment by JOE1994** [comment]
Below is a summary of results after flashing and running some examples on my `NucleoF429ZI` board.
I've found that the `lua_hello` app panics at runtime when compiled with this branch :disappointed: 

### `lua_hello` example fails to build with newlib version newer than **3.0.0.20180831**
* I need to retry building a newer version of newlib to reproduce the error message, but the error phrase was as below.
  **`undefined reference to '__locale_ctype_ptr'`**
* `lua_hello` from master branch of `libtock-c` works as expected on `NucleoF429ZI` board

### Tested examples (5 examples)
#### Successful examples (4)
* [x] blink
* [x] buttons
* [x] c_hello
* [x] cxx_hello

#### Failed examples (1)
* [ ] lua_hello : builds without any errors, but panics at runtime
   The error message **"ThumbBit false !!ERROR - Cortex M Thumb only!"** from the report seems to be important.
```
panicked at 'Process lua-hello had a fault', /home/lonelyjoe/.rustup/toolchains/nightly-2020-06-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:16:9
        Kernel version release-1.5-708-g455c5a0ac

---| No debug queue found. You can set it with the DebugQueue component.

---| Fault Status |---
Invalid State Usage Fault:          true
Forced Hard Fault:                  true
Fault Status Register (CFSR):       0x00020000
Hard Fault Status Register (HFSR):  0x40000000

---| App Status |---
App: lua-hello   -   [Fault]
 Events Queued: 0   Syscall Count: 5   Dropped Callback Count: 0
 Restart Count: 0
 Last Syscall: Some(MEMOP { operand: 1, arg0: 812 })

 ��╔��═��═��═��═��═��═��═��═��═��═��═��╤��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��╗
 ��║  Address  ��│ Region Name    Used | Allocated (bytes)  ��║
 ��╚0x20008000��═��╪��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��═��╝
             ��│ ��▼ Grant        1020 |   1020          
  0x20007C04 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─
             ��│ Unused
  0x20005B30 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─
             ��│ ��▲ Heap          812 |   9216               S
  0x20005804 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─ R
             ��│ Data           3076 |   3076               A
  0x20004C00 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─ M
             ��│ ��▼ Stack         272 |   3072          
  0x20004AF0 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─
             ��│ Unused
  0x20004000 ��┴��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─
             .....
  0x08060000 ��┬��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─ F
             ��│ App Flash    131024                        L
  0x08040030 ��┼��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─ A
             ��│ Protected        48                        S
  0x08040000 ��┴��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─��─ H

  R0 : 0x20004B28    R6 : 0x2000580C
  R1 : 0x080434BD    R7 : 0x00000000
  R2 : 0x00000000    R8 : 0x08041141
  R3 : 0x20004B24    R10: 0x00000000
  R4 : 0x20005984    R11: 0x00000000
  R5 : 0x00000000    R12: 0x08040030
  R9 : 0x20004C00 (Static Base Register)
  SP : 0x20004AF0 (Process Stack Pointer)
  LR : 0x080453D5
  PC : 0x0804D13C
 YPC : 0x0804043A

 APSR: N 0 Z 1 C 1 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit false !!ERROR - Cortex M Thumb only!

 Cortex-M MPU
  Region 0: [0x20004000:0x20008000], length: 16384 bytes; ReadWrite (0x3)
    Sub-region 0: [0x20004000:0x20004800], Enabled
    Sub-region 1: [0x20004800:0x20005000], Enabled
    Sub-region 2: [0x20005000:0x20005800], Enabled
    Sub-region 3: [0x20005800:0x20006000], Enabled
    Sub-region 4: [0x20006000:0x20006800], Disabled
    Sub-region 5: [0x20006800:0x20007000], Disabled
    Sub-region 6: [0x20007000:0x20007800], Disabled
    Sub-region 7: [0x20007800:0x20008000], Disabled
  Region 1: [0x08040000:0x08060000], length: 131072 bytes; ReadOnly (0x6)
    Sub-region 0: [0x08040000:0x08044000], Enabled
    Sub-region 1: [0x08044000:0x08048000], Enabled
    Sub-region 2: [0x08048000:0x0804C000], Enabled
    Sub-region 3: [0x0804C000:0x08050000], Enabled
    Sub-region 4: [0x08050000:0x08054000], Enabled
    Sub-region 5: [0x08054000:0x08058000], Enabled
    Sub-region 6: [0x08058000:0x0805C000], Enabled
    Sub-region 7: [0x0805C000:0x08060000], Enabled
  Region 2: Unused
  Region 3: Unused
  Region 4: Unused
  Region 5: Unused
  Region 6: Unused
  Region 7: Unused

To debug, run `make debug RAM_START=0x20004000 FLASH_INIT=0x8040059`
in the app's folder and open the .lst file.
```

**Comment by ppannuto** [comment]
Some quick googling suggests that `undefined reference to '__locale_ctype_ptr'` can be resolved with a complete `make clean`, though I'd understand if it's more complex than that in practice.

---

The "Thumb Bit False" is usually an indicator of a bad jump quite probably a corrupted stack frame that returned somewhere silly, but hard to know without digging in. I don't have any time this week to dig deeply at this I'm afraid, but maybe can try next week.

**Comment by phil-levis** [comment]
Bump -- @ppannuto do you want to pick this back up?

**Comment by ppannuto** [comment]
Replaced by #165.
